cars <- c(1,3,6,4,9)
trucks <- c(2,5,4,5,12)
g_range <- range(0, cars, trucks)
plot(cars, type='o', col='blue',ylim = g_range, axes = FALSE, ann = FALSE)
axis(1, at=1:5, lab=c("Mon", "Tues","Wed", "Thurs", "Fri"))
axis(2, las=1, at=4*0:g_range[2])
box()
lines(trucks, type='o', pch=22, lty=2, col='red')
title(main="Auto Vehicles")
